swagger: '2.0'
info:
  version: '1.0.0'
  title: Individual Leisure Travel - Pay and Issue
  description: Pay and Issue API accepts the CustomerReferenceNumber as input along with Payment information and issues the CRN and return the Policy and other documents
  contact:
    name: Solartis Support
    email: info@solartis.net
host: sademokb.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: This API issues the Policy from the CRN
      operationId: Pay_Issue
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "Pay_Issue"
        - name: Pay_Issue
          in: body
          description: Pay_Issue/traveler details
          required: true
          schema:
            $ref: '#/definitions/Pay_Issue_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/Pay_Issue_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Pay_Issue_Request:
    type: object
    required:
     - ServiceRequestDetail
     - PolicyInformation
    properties:
      EndClientUserUniqueSessionId:
        type: string
      EndClientUserBrowserSessionId:
        type: string
      EndClientUserBrowserInformation:
        type: string
      PaaSClientIPAddress:
        type: string
      ClientUniqueRequestID:
        type: string
      ServiceRequestDetail:
        type: object
        required:
          - OwnerId
          - RegionCode
          - Token
          - ServiceRequestVersion
          - ServiceResponseVersion
          - ResponseType
        properties:
          ServiceRequestVersion:
            type: string
            default: "1.0"
          ServiceResponseVersion:
            type: string
            default: "1.0"
          OwnerId:
            type: string
            default: "15"
          ResponseType:
            type: string
            enum: ["JSON","XML"]
            default: "JSON"
          RegionCode:
            type: string
            default: "US"
          Token:
            type: string
            default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
          UserName:
            type: string
            default: "travelagent"
          LanguageCode:
            type: string
            default: "en"
          BrowserIp:
            type: string
      PolicyInformation:
        type: object
        required:
          - ProducerCode
          - ProductVerID
          - ProductID
          - ProductNumber
          - ProductVerNumber
          - OwnerId
        properties:
          ProductVerID:
            type: string
            default: "706"
          ProductID:
            type: string
            default: "619"
          ProductNumber:
            type: string
            default: "ILT"
          ProductVerNumber:
            type: string
            default: "1.0"
          ProducerCode:
            type: string
            default: "86201"
          OwnerId:
            type: string
            default: "15"
          CustomerNumber:
            type: string
          RoleID:
            type: string
            default: "5"
          RoleName:
            type: string
            default: "Agent"
          RoleType:
            type: string
            default: "User"
          EventName:
            type: string
            default: "Pay_Issue"
          CardNumber:
            type: string
            enum: ["5555555555554444","6011000990139424","3530111333300000","4012888888881881","347712669659320"]
          CVV:
            type: string
            default: "123"
          ExpiryMonth:
            type: string
          ExpiryYear:
            type: string
            enum: ["2018","2019","2020","2021","2022","2023"]
          PayerName:
            type: string
          PayerAddress1:
            type: string
          PayerAddress2:
            type: string
          PayerCity:
            type: string
          PayerState:
            type: string
          PayerCountry:
            type: string
            default: "US"
          PayerZipcode:
            type: string
          PayerEmail:
            type: string
          PayerPhone:
            type: string
          PaymentMethod:
            type: string
            enum: ["Credit Card"]
          CardType:
            type: string
            enum: ["MasterCard","Visa","JCB","Discover","American Express"]
  Pay_Issue_Success_Response:
    type: object
    required:
      - RequestStatus
      - PolicyBatch
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      CustomerName:
        type: string
      CustomerReferenceNumber:
        type: string
      PolicyBatch:
        type: object
        properties:
          PaymentStatus:
            type: string
          DepartureDate:
            type: string
          ReturnDate:
            type: string
          PolicyEffectiveDate:
            type: string
          Documents:
            type: array
            items:
              properties:
                DocumentType:
                  type: string
                DocumentName:
                  type: string
                DocumentURL:
                  type: string
          Policies:
            type: array
            items:
              properties:
                PolicyNumber:
                  type: string
                TravelerIndex:
                  type: string
                TravelerPremium:
                  type: string
                Documents:
                  type: array
                  items:
                    properties:
                      DocumentType:
                        type: string
                      DocumentName:
                        type: string
                      DocumentURL:
                        type: string
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string