swagger: '2.0'
info:
  version: '1.0.0'
  title: Individual Leisure Travel - Save Customer
  description: Save Customer API is to save the traveler information and generate a unique identifier which can be referenced to a CSR at any given point in the business flow. From which the CSR would pickup the CRN number and issue a quote in case the user not able to proceed with the flow by Underwriting rules
  contact:
    name: Solartis Support
    email: info@solartis.net
host: sademokb.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Save traveler information and plan information
      operationId: SaveCustomer
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "CreateCustomer"
        - name: CreateCustomer
          in: body
          description: Save customer/traveler details
          required: true
          schema:
            $ref: '#/definitions/SaveCustomer_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/SaveCustomer_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  SaveCustomer_Request:
    type: object
    required:
     - ServiceRequestDetail
     - CustomerInformation
    properties:
      EndClientUserUniqueSessionId:
        type: string
      EndClientUserBrowserSessionId:
        type: string
      EndClientUserBrowserInformation:
        type: string
      PaaSClientIPAddress:
        type: string
      ClientUniqueRequestID:
        type: string
      ServiceRequestDetail:
        type: object
        required:
          - OwnerId
          - RegionCode
          - Token
          - ServiceRequestVersion
          - ServiceResponseVersion
          - ResponseType
        properties:
          ServiceRequestVersion:
            type: string
            default: "1.0"
          ServiceResponseVersion:
            type: string
            default: "1.0"
          OwnerId:
            type: string
            default: "15"
          ResponseType:
            type: string
            enum: ["JSON","XML"]
            default: "JSON"
          RegionCode:
            type: string
            default: "US"
          Token:
            type: string
            default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
          UserName:
            type: string
            default: "travelagent"
          LanguageCode:
            type: string
            default: "en"
          BrowserIp:
            type: string
      CustomerInformation:
        type: object
        required:
          - ProducerCode
          - OwnerId
          - PlanName
          - PlanCode
          - StateCode
          - StateName
          - PlanType
          - EventName
          - ProductVerID
          - ProductID
          - ProductNumber
          - ProductVerNumber
          - TravelerList
        properties:
          ProductVerID:
            type: string
            default: "706"
          ProductID:
            type: string
            default: "619"
          ProductNumber:
            type: string
            default: "ILT"
          ProductVerNumber:
            type: string
            default: "1.0"
          ProducerCode:
            type: string
            default: "86201"
          OwnerId:
            type: string
            default: "15"
          CustomerReferenceNumber:
            type: string
          PlanName:
            type: string
            enum: ["Air Ticket Protector","Classic Plus","Premier","Premier Annual","Basic Annual","Medical Only Annual","Renter's Collision"]
          PlanCode:
            type: string
            enum: ["1","2","3","4","9","10","11"]
          PlanType:
            type: string
            enum: ["Single Trip","Annual","Renter's Collision"]
          DepartureDate:
            type: string
            format: date
          ReturnDate:
            type: string
            format: date
          DepositDate:
            type: string
            format: date
          TripCancellationCoverage:
            type: string
            enum: ["","With Trip Cancellation","With Trip Cancellation for Any Reason"]
          DestinationCountry:
            type: string
          PolicyEffectiveDate:
            type: string
            format: date
          RentalStartDate:
            type: string
            format: date
          RentalEndDate:
            type: string
            format: date
          RentalLimit:
            type: string
            default: "35000"
          NumberOfRentalCars:
            type: string
            default: "1"
          StateCode:
            type: string
          StateName:
            type: string
          QuoteType:
            type: string
            default: "New Business"
          EventName:
            type: string
            default: "CreateCustomer"
          TravelerList:
            type: array
            items:
              required:
                - TravelerDOB
              properties:
                TravelerDOB:
                  type: string
                  format: date
                TravelCost:
                  type: string
                FirstName:
                  type: string
                LastName:
                  type: string
                AddressLine1:
                  type: string
                AddressLine2:
                  type: string
                City:
                  type: string
                State:
                  type: string
                StateCode:
                  type: string
                Country:
                  type: string
                Zipcode:
                  type: string
                Phone:
                  type: string
                Email:
                  type: string
                TravelerIndex:
                  type: string
  SaveCustomer_Success_Response:
    type: object
    required:
      - RequestStatus
      - CustomerInformation
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      CustomerInformation:
        type: object
        properties:
          CustomerReferenceNumber:
            type: string
          PlanCode:
            type: string
          PlanName:
            type: string
          PlanType:
            type: string
          ProducerCode:
            type: string
          StateName:
            type: string
          StateCode:
            type: string
          OwnerId:
            type: string
          EventName:
            type: string
          PolicyEffectiveDate:
            type: string
            format: date
          TravelerList:
            type: array
            items:
              properties:
                TravelerDOB:
                  type: string
                  format: date
                TravelCost:
                  type: string
                FirstName:
                  type: string
                LastName:
                  type: string
                AddressLine1:
                  type: string
                AddressLine2:
                  type: string
                City:
                  type: string
                State:
                  type: string
                StateCode:
                  type: string
                Country:
                  type: string
                Zipcode:
                  type: string
                Phone:
                  type: string
                Email:
                  type: string
                TravelerIndex:
                  type: string
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string